language: cpp

os:
  - linux
  - osx

dist: trusty
sudo: false

addons:
  apt:
    sources:
    - 'ubuntu-toolchain-r-test'
    packages:
    - g++-multilib
    - binutils-gold
    - libcurl4-openssl-dev
    - g++-7
    - p7zip-full

python: '2.7'

env:
  global:
  - URL_PREFIX=https://v8.eyeofiles.com/v8-3cdaf01c4043e19965efc5ef48df5314960b898f/
  matrix:
  - BUILD_ACTION=test
  - BUILD_ACTION=android_arm ANDROID_NDK_ROOT=${TRAVIS_BUILD_DIR}/third_party/android-ndk-r16b
  - BUILD_ACTION=android_x86 ANDROID_NDK_ROOT=${TRAVIS_BUILD_DIR}/third_party/android-ndk-r16b
  - BUILD_ACTION=android_arm64 ANDROID_NDK_ROOT=${TRAVIS_BUILD_DIR}/third_party/android-ndk-r16b

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install p7zip; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-7 CC=gcc-7; fi
  - bash .travis/prepare-prebuilt-v8.sh
  - sed -i.bak '/third_party\/v8/d' dependencies
  - ./ensure_dependencies.py
  - if [[ -n "$ANDROID_NDK_ROOT" && "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip -O third_party/android-ndk.zip ; fi
  - if [[ -n "$ANDROID_NDK_ROOT" && "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://dl.google.com/android/repository/android-ndk-r16b-darwin-x86_64.zip -O third_party/android-ndk.zip ; fi
  - if [[ -n "$ANDROID_NDK_ROOT" ]]; then unzip -q third_party/android-ndk.zip -d third_party/ ; fi

script:
  - travis_wait 30 make ${BUILD_ACTION} LIBV8_LIB_DIR=../third_party/prebuilt-v8/ LIBV8_INCLUDE_DIR=third_party/prebuilt-v8/include

notifications:
  email: false
