language: cpp

os:
  - linux
  - osx

dist: trusty
sudo: false

compiler: clang

addons:
  apt:
    sources:
    - 'ubuntu-toolchain-r-test'
    packages:
    - binutils-gold
    - libcurl4-openssl-dev
    - p7zip-full

python: '2.7'

env:
  global:
  - URL_PREFIX=https://v8.eyeofiles.com/v8-4fc9a2fe7f8a7ef1e7966185b39b3b541792669a/
  - ANDROID_NDK_ROOT=${TRAVIS_BUILD_DIR}/third_party/android-ndk-r16b
  - libv8_show_warnings="true"
  matrix:
  - ABP_OS_SCRIPT=nix
  - ABP_OS_SCRIPT=android

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install p7zip; fi
  - ./ensure_dependencies.py
  - if [[ "${ABP_OS_SCRIPT}" == "android" && "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip -O third_party/android-ndk.zip ; fi
  - if [[ "${ABP_OS_SCRIPT}" == "android" && "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://dl.google.com/android/repository/android-ndk-r16b-darwin-x86_64.zip -O third_party/android-ndk.zip ; fi
  - if [[ "${ABP_OS_SCRIPT}" == "android" ]]; then unzip -q third_party/android-ndk.zip -d third_party/ ; fi

script:
  - bash ./.travis/${ABP_OS_SCRIPT}-script.sh

notifications:
  email: false
