version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x64
- Win32 
clone_depth: 1
init:
- cmd: echo %Platform% %Configuration%
install:
- cmd: .appveyor\prepare-prebuilt-v8.cmd
- cmd: ensure_dependencies.py
environment:
  URL_PREFIX: https://v8.eyeofiles.com/v8-4fc9a2fe7f8a7ef1e7966185b39b3b541792669a/
before_build:
- cmd: set "GYP_DEFINES=libv8_include_dir=third_party/prebuilt-v8/include libv8_lib_dir=../../third_party/prebuilt-v8"
- cmd: createsolution.bat
- cmd: >-
    if "%Platform%"=="Win32" set arch="ia32"

    if "%Platform%"=="x64" set arch="x64"

build_script:
- cmd: msbuild "build/%arch%/libadblockplus.sln" /m /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
test_script:
- cmd: build\%arch%\%Configuration%\tests.exe --gtest_output=xml:tests.xml
after_test:
- ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\tests.xml))
deploy: off
